### ISSUE TITLE
make real REST API calls

### ISSUE THREAD

**Issue by Nodnarb12500** [Nodnarb12500/gimped-REST-API#22]
Example
app // modify a row in the database
.post("/api/modify", (req, res) => {
  // do stuff
}

.patch("/api/modify", (req, res) => {
  // do stuff
}

this and several other things would work just the same as before I think. But since I'm not using a client in most cases that would use a proper REST API this is very low priority.

**Comment by Nodnarb12500** [comment]
extra help isnt really wanted but if someone wants to fuck around with it and i test it and it works. im curious to see how PRs work

**Comment by Nodnarb12500** [comment]
ill add the label anyway

**Comment by kyojurocode** [comment]
hey, I would like to work on this issue, can you plz guide me!!

**Comment by Nodnarb12500** [comment]
what do you need guided on? i dont really know how PRs work unfortunately, but i got a someone that might be able to explain it to me

EDIT: looks like i should make a separate branch to allow pull requests

**Comment by Nodnarb12500** [comment]
do you need docs on how to use the server? I made some docs in the wiki tab. They are incomplete but they are better then the few lines i had before in the README file

**Comment by kyojurocode** [comment]
Yes please do assign me..

**Comment by Nodnarb12500** [comment]
> Yes please do assign me..

I don't know how pull requests work, but I assume you might be able to make one and create the changes? im pretty new to actually using github

**Comment by Nodnarb12500** [comment]
okay i think i just dont know what a PR is and i think i figured it out now

EDIT: might take me a minute to find all the buttons to click

**Comment by Nodnarb12500** [comment]
Let me know if it worked lol

**Comment by kyojurocode** [comment]
I am working on it

**Comment by kyojurocode** [comment]
can you plz describe the issue...like what you needed to worked on!!!

**Comment by Nodnarb12500** [comment]
in routes/api.js the API calls only use GET and POST (they might all be POST now) instead of using the proper API calls that a REST API should have. but I want to keep my shitty post requests to.

app
.post("/modify", (req, res) => {
//do stuff
})

.put("/modify", (req, res) => {
// do the same stuff?
});

**Comment by Nodnarb12500** [comment]
thank you for your patience while im learning how this stuff works. I've noticed I've done some unnecessary things like giving you access to this repo and a branch on this repo. i know know that PRs can happen from forks outside this repo
